name: cli_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  syncfusion_flutter_core: ^19.4.40
  collection: ^1.15.0
  scrollable_positioned_list: ^0.2.3
  indexed_list_view: ^2.0.1
  googleapis: ^7.0.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

